/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface PlayerProfile {
  'xp' : bigint,
  'bestTimes' : Array<[string, Time]>,
  'username' : string,
  'wordsFound' : bigint,
  'level' : bigint,
  'completedPuzzles' : Array<bigint>,
  'lastLogin' : Time,
}
export interface PuzzleMeta { 'id' : bigint }
export type Time = bigint;
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createOrUpdateProfile' : ActorMethod<[string], undefined>,
  'generatePuzzle' : ActorMethod<[bigint], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [PlayerProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDailyChallenge' : ActorMethod<[string], [] | [PuzzleMeta]>,
  'getPuzzle' : ActorMethod<[bigint], [] | [PuzzleMeta]>,
  'getTopPlayers' : ActorMethod<[], Array<[Principal, bigint]>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [PlayerProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[PlayerProfile], undefined>,
  'setDailyChallenge' : ActorMethod<[string, PuzzleMeta], undefined>,
  'submitScore' : ActorMethod<[bigint, bigint, Time], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];