/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const PlayerProfile = IDL.Record({
  'xp' : IDL.Nat,
  'bestTimes' : IDL.Vec(IDL.Tuple(IDL.Text, Time)),
  'username' : IDL.Text,
  'wordsFound' : IDL.Nat,
  'level' : IDL.Nat,
  'completedPuzzles' : IDL.Vec(IDL.Nat),
  'lastLogin' : Time,
});
export const PuzzleMeta = IDL.Record({ 'id' : IDL.Nat });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createOrUpdateProfile' : IDL.Func([IDL.Text], [], []),
  'generatePuzzle' : IDL.Func([IDL.Nat], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(PlayerProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDailyChallenge' : IDL.Func([IDL.Text], [IDL.Opt(PuzzleMeta)], ['query']),
  'getPuzzle' : IDL.Func([IDL.Nat], [IDL.Opt(PuzzleMeta)], ['query']),
  'getTopPlayers' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Nat))],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(PlayerProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([PlayerProfile], [], []),
  'setDailyChallenge' : IDL.Func([IDL.Text, PuzzleMeta], [], []),
  'submitScore' : IDL.Func([IDL.Nat, IDL.Nat, Time], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const PlayerProfile = IDL.Record({
    'xp' : IDL.Nat,
    'bestTimes' : IDL.Vec(IDL.Tuple(IDL.Text, Time)),
    'username' : IDL.Text,
    'wordsFound' : IDL.Nat,
    'level' : IDL.Nat,
    'completedPuzzles' : IDL.Vec(IDL.Nat),
    'lastLogin' : Time,
  });
  const PuzzleMeta = IDL.Record({ 'id' : IDL.Nat });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createOrUpdateProfile' : IDL.Func([IDL.Text], [], []),
    'generatePuzzle' : IDL.Func([IDL.Nat], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(PlayerProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDailyChallenge' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(PuzzleMeta)],
        ['query'],
      ),
    'getPuzzle' : IDL.Func([IDL.Nat], [IDL.Opt(PuzzleMeta)], ['query']),
    'getTopPlayers' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Nat))],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(PlayerProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([PlayerProfile], [], []),
    'setDailyChallenge' : IDL.Func([IDL.Text, PuzzleMeta], [], []),
    'submitScore' : IDL.Func([IDL.Nat, IDL.Nat, Time], [], []),
  });
};

export const init = ({ IDL }) => { return []; };